services:
  node1:
    build: .
    ports:
      - '3001:3000'
    environment:
      - NODE_ID=node-1
      - HTTP_PORT=3000
      - PEERS=http://node2:3000,http://node3:3000
    volumes:
      - ./data:/app/data

  node2:
    build: .
    ports:
      - '3002:3000'
    environment:
      - NODE_ID=node-2
      - HTTP_PORT=3000
      - PEERS=http://node1:3000,http://node3:3000
    volumes:
      - ./data:/app/data

  node3:
    build: .
    ports:
      - '3003:3000'
    environment:
      - NODE_ID=node-3
      - HTTP_PORT=3000
      - PEERS=http://node1:3000,http://node2:3000
    volumes:
      - ./data:/app/data
